// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MassoudBooksSr.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MassoudBookSerialization {

  /// <summary>Holder for reflection information generated from MassoudBooksSr.proto</summary>
  public static partial class MassoudBooksSrReflection {

    #region Descriptor
    /// <summary>File descriptor for MassoudBooksSr.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MassoudBooksSrReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRNYXNzb3VkQm9va3NTci5wcm90bxIYTWFzc291ZEJvb2tTZXJpYWxpemF0",
            "aW9uItkDCgRCb29rEgwKBG5hbWUYASABKAkSOwoIY2F0YWdvcnkYAiABKA4y",
            "KS5NYXNzb3VkQm9va1NlcmlhbGl6YXRpb24uQm9vay5DYXRhZ29yaWVzEkMK",
            "DXJlYWRpbmdTdGF0dXMYAyABKA4yLC5NYXNzb3VkQm9va1NlcmlhbGl6YXRp",
            "b24uQm9vay5SZWFkaW5nU3RhdHVzEgsKA3RhZxgEIAMoCRINCgVwYWdlcxgF",
            "IAEoBSKNAQoKQ2F0YWdvcmllcxIPCgtBbnlDYXRhZ29yeRAAEggKBE1hdGgQ",
            "ARILCgdHYW1lRGV2EAISCgoGQ1NoYXJwEAMSCAoESmF2YRAEEgYKAkNzEAUS",
            "BwoDQ3BwEAYSDQoJRW1tYmVkZGVkEAcSCwoHUHlBbmRNbBAIEgcKA0FydBAJ",
            "EgsKB0FuZHJvaWQQCiKUAQoNUmVhZGluZ1N0YXR1cxIUChBBbnlSZWFkaW5n",
            "U3RhdHVzEAASCwoHUmVhZGluZxABEg0KCVdhbm5hUmVhZBACEg4KCldhbm5h",
            "UmVhZDIQAxISCg5ZZXRUb1dhbm5hUmVhZBAFEhIKDkRlbGF5ZWRSZWFkaW5n",
            "EAYSDAoIRmluaXNoZWQQBxILCgdEcm9wcGVkEAgiTQoLVG9TZXJpYWxpemUS",
            "MAoIQWxsQm9va3MYASADKAsyHi5NYXNzb3VkQm9va1NlcmlhbGl6YXRpb24u",
            "Qm9vaxIMCgRUYWdzGAIgAygJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MassoudBookSerialization.Book), global::MassoudBookSerialization.Book.Parser, new[]{ "Name", "Catagory", "ReadingStatus", "Tag", "Pages" }, null, new[]{ typeof(global::MassoudBookSerialization.Book.Types.Catagories), typeof(global::MassoudBookSerialization.Book.Types.ReadingStatus) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MassoudBookSerialization.ToSerialize), global::MassoudBookSerialization.ToSerialize.Parser, new[]{ "AllBooks", "Tags" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Book : pb::IMessage<Book> {
    private static readonly pb::MessageParser<Book> _parser = new pb::MessageParser<Book>(() => new Book());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Book> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MassoudBookSerialization.MassoudBooksSrReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Book() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Book(Book other) : this() {
      name_ = other.name_;
      catagory_ = other.catagory_;
      readingStatus_ = other.readingStatus_;
      tag_ = other.tag_.Clone();
      pages_ = other.pages_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Book Clone() {
      return new Book(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "catagory" field.</summary>
    public const int CatagoryFieldNumber = 2;
    private global::MassoudBookSerialization.Book.Types.Catagories catagory_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MassoudBookSerialization.Book.Types.Catagories Catagory {
      get { return catagory_; }
      set {
        catagory_ = value;
      }
    }

    /// <summary>Field number for the "readingStatus" field.</summary>
    public const int ReadingStatusFieldNumber = 3;
    private global::MassoudBookSerialization.Book.Types.ReadingStatus readingStatus_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MassoudBookSerialization.Book.Types.ReadingStatus ReadingStatus {
      get { return readingStatus_; }
      set {
        readingStatus_ = value;
      }
    }

    /// <summary>Field number for the "tag" field.</summary>
    public const int TagFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_tag_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> tag_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Tag {
      get { return tag_; }
    }

    /// <summary>Field number for the "pages" field.</summary>
    public const int PagesFieldNumber = 5;
    private int pages_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Pages {
      get { return pages_; }
      set {
        pages_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Book);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Book other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Catagory != other.Catagory) return false;
      if (ReadingStatus != other.ReadingStatus) return false;
      if(!tag_.Equals(other.tag_)) return false;
      if (Pages != other.Pages) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Catagory != 0) hash ^= Catagory.GetHashCode();
      if (ReadingStatus != 0) hash ^= ReadingStatus.GetHashCode();
      hash ^= tag_.GetHashCode();
      if (Pages != 0) hash ^= Pages.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Catagory != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Catagory);
      }
      if (ReadingStatus != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ReadingStatus);
      }
      tag_.WriteTo(output, _repeated_tag_codec);
      if (Pages != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Pages);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Catagory != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Catagory);
      }
      if (ReadingStatus != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReadingStatus);
      }
      size += tag_.CalculateSize(_repeated_tag_codec);
      if (Pages != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pages);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Book other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Catagory != 0) {
        Catagory = other.Catagory;
      }
      if (other.ReadingStatus != 0) {
        ReadingStatus = other.ReadingStatus;
      }
      tag_.Add(other.tag_);
      if (other.Pages != 0) {
        Pages = other.Pages;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            catagory_ = (global::MassoudBookSerialization.Book.Types.Catagories) input.ReadEnum();
            break;
          }
          case 24: {
            readingStatus_ = (global::MassoudBookSerialization.Book.Types.ReadingStatus) input.ReadEnum();
            break;
          }
          case 34: {
            tag_.AddEntriesFrom(input, _repeated_tag_codec);
            break;
          }
          case 40: {
            Pages = input.ReadInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Book message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Catagories {
        [pbr::OriginalName("AnyCatagory")] AnyCatagory = 0,
        [pbr::OriginalName("Math")] Math = 1,
        [pbr::OriginalName("GameDev")] GameDev = 2,
        [pbr::OriginalName("CSharp")] Csharp = 3,
        [pbr::OriginalName("Java")] Java = 4,
        [pbr::OriginalName("Cs")] Cs = 5,
        [pbr::OriginalName("Cpp")] Cpp = 6,
        [pbr::OriginalName("Emmbedded")] Emmbedded = 7,
        [pbr::OriginalName("PyAndMl")] PyAndMl = 8,
        [pbr::OriginalName("Art")] Art = 9,
        [pbr::OriginalName("Android")] Android = 10,
      }

      public enum ReadingStatus {
        [pbr::OriginalName("AnyReadingStatus")] AnyReadingStatus = 0,
        [pbr::OriginalName("Reading")] Reading = 1,
        [pbr::OriginalName("WannaRead")] WannaRead = 2,
        [pbr::OriginalName("WannaRead2")] WannaRead2 = 3,
        [pbr::OriginalName("YetToWannaRead")] YetToWannaRead = 5,
        [pbr::OriginalName("DelayedReading")] DelayedReading = 6,
        [pbr::OriginalName("Finished")] Finished = 7,
        [pbr::OriginalName("Dropped")] Dropped = 8,
      }

    }
    #endregion

  }

  public sealed partial class ToSerialize : pb::IMessage<ToSerialize> {
    private static readonly pb::MessageParser<ToSerialize> _parser = new pb::MessageParser<ToSerialize>(() => new ToSerialize());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ToSerialize> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MassoudBookSerialization.MassoudBooksSrReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToSerialize() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToSerialize(ToSerialize other) : this() {
      allBooks_ = other.allBooks_.Clone();
      tags_ = other.tags_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToSerialize Clone() {
      return new ToSerialize(this);
    }

    /// <summary>Field number for the "AllBooks" field.</summary>
    public const int AllBooksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MassoudBookSerialization.Book> _repeated_allBooks_codec
        = pb::FieldCodec.ForMessage(10, global::MassoudBookSerialization.Book.Parser);
    private readonly pbc::RepeatedField<global::MassoudBookSerialization.Book> allBooks_ = new pbc::RepeatedField<global::MassoudBookSerialization.Book>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MassoudBookSerialization.Book> AllBooks {
      get { return allBooks_; }
    }

    /// <summary>Field number for the "Tags" field.</summary>
    public const int TagsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_tags_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> tags_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Tags {
      get { return tags_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ToSerialize);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ToSerialize other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!allBooks_.Equals(other.allBooks_)) return false;
      if(!tags_.Equals(other.tags_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= allBooks_.GetHashCode();
      hash ^= tags_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      allBooks_.WriteTo(output, _repeated_allBooks_codec);
      tags_.WriteTo(output, _repeated_tags_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += allBooks_.CalculateSize(_repeated_allBooks_codec);
      size += tags_.CalculateSize(_repeated_tags_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ToSerialize other) {
      if (other == null) {
        return;
      }
      allBooks_.Add(other.allBooks_);
      tags_.Add(other.tags_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            allBooks_.AddEntriesFrom(input, _repeated_allBooks_codec);
            break;
          }
          case 18: {
            tags_.AddEntriesFrom(input, _repeated_tags_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
